Add fvisibility=hidden required by pybind11
Fixes
```
tiledb/core.cc:77:8: error: ‘tiledbpy::BufferInfo’ declared with greater visibility than the type of its field ‘tiledbpy::BufferInfo::data’ [-Werror=attribu
tes]
```