Fix warnings on clang and gcc (#583)
* Add setup.py support for Werror builds (default for debug)

cython is TODO because there are hard-coded errors from cython
deprecated usage that come directly from preprocessor warns rather
than deprecation marks.

* Add TILEDB_TIME_* type mappings

* Fix sign-compare error

* Fix std::move Werrors in fragment.cc

```
tiledb/fragment.cc:137:12: error: local variable 'limits' will be copied despite being returned by name
      [-Werror,-Wreturn-std-move]
    return limits;
           ^~~~~~
tiledb/fragment.cc:137:12: note: call 'std::move' explicitly to avoid copying
    return limits;
           ^~~~~~
           std::move(limits)
```

* Add missing cmath include

* Remove unnecessary numpy/arrayobject include

* Fix warnings in core and npbuffer.cc on clang

* Enable werror on mac/linux CI builds

* Add fvisibility=hidden required by pybind11

Fixes
```
tiledb/core.cc:77:8: error: ‘tiledbpy::BufferInfo’ declared with greater visibility than the type of its field ‘tiledbpy::BufferInfo::data’ [-Werror=attribu
tes]
```

* Fix warnings in debug build

* Add exception translator to fragment.cc

With fvisibility=hidden, TileDBPyError exception class is different in each TU,
so exceptions are not handled correctly in fragments.cc code. Eventually
this code will be in a single module, but fix for now by adding
translator in fragments.cc

* Fix -Werror,-Wpessimizing-move

* Fix -Werror,-Wunused-variable